name: Deploy Changed Skills

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to compare against'
        required: false
        default: 'main'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  changes:
    runs-on: ubuntu-latest
    outputs:
      changed1: ${{ steps.filter1.outputs.changed }}
      changed2: ${{ steps.filter2.outputs.changed }}
      files: ${{ steps.parsed_files.outputs.group1 }}
    steps:

    - name: Checkout branch
      uses: actions/checkout@v2

    - uses: dorny/paths-filter@v2
      if: ${{ github.event_name != 'workflow_dispatch' }}
      id: filter1
      with:
        # Enable listing of files matching each filter.
        # Paths to files will be available in `${FILTER_NAME}_files` output variable.
        # Paths will be escaped and space-delimited.
        # Output is usable as command-line argument list in Linux shell
        list-files: shell

        # In this example all changed files are passed to the following action to do
        # some custom processing.
        filters: |
          changed:
            - added|modified: '*/main.csx'
            - added|modified: '*/main.py'
            - added|modified: '*/main.js'

    - uses: dorny/paths-filter@v2
      if: ${{ github.event_name == 'workflow_dispatch' }}
      id: filter2
      with:
        base: ${{ github.event.inputs.branch }}
        # Enable listing of files matching each filter.
        # Paths to files will be available in `${FILTER_NAME}_files` output variable.
        # Paths will be escaped and space-delimited.
        # Output is usable as command-line argument list in Linux shell
        list-files: shell

        # In this example all changed files are passed to the following action to do
        # some custom processing.
        filters: |
          changed:
            - added|modified: '*/main.csx'
            - added|modified: '*/main.py'
            - added|modified: '*/main.js'

    - name: Parse changed files
      uses: shana/action-regex-match@99fcf932f925c32af80c349fc37fefad16fb18fd
      id: parsed_files
      with:
        text: ${{ steps.filter1.outputs.changed_files }} ${{ steps.filter2.outputs.changed_files }}
        regex: '(?<!\S)([\-0-9a-zA-Z]*)\/main\.[py|csx|js]+(?!\S)'
        flags: gm


  deploy:
    needs: changes
    if: ${{ needs.changes.outputs.changed1 == 'true' || needs.changes.outputs.changed2 == 'true' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: List changed skills
      if: github.event_name == 'pull_request'
      run: script/deploy -n ${{ needs.changes.outputs.files }}

    - name: Deploy changed skills
      if: github.event_name != 'pull_request'
      # TODO: install abbot and take out the -n flag here
      run: script/deploy -n ${{ needs.changes.outputs.files }}
